{
 "title": "Mlops",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Api Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{filename=\"/app/res18api.log\"} |= ``"
    }
   ]
  },
  {
   "title": "request_errors_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "request_errors_total{instance=\"flask-app:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Error List", "type": "alertlist", "gridPos": { "h": 6, "w": 6, "x": 0, "y": 8 } },
  {
   "title": "request_count_total",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "request_count_total{instance=\"flask-app:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "process_cpu_seconds_total{instance=\"flask-app:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rate(request_errors_total[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(request_latency_seconds_sum[3m]) / rate(request_latency_seconds_count[3m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Is Flask(API) Working",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "up{instance=\"flask-app:8000\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}