# Use the official lightweight Python image
FROM pytorch/pytorch
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Asia/Jerusalem

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY copy_docker/*  /app/.

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

#install packages for logs and set logs 
RUN apt update -y && apt install nano wget unzip -y &&\
    wget https://github.com/grafana/loki/releases/download/v2.8.1/promtail-linux-amd64.zip && \
    unzip promtail-linux-amd64.zip && \
    mv promtail-linux-amd64 /usr/local/bin/promtail && \
    chmod +x /usr/local/bin/promtail && \
    wget https://github.com/grafana/loki/releases/download/v2.8.1/loki-linux-amd64.zip && \
    unzip loki-linux-amd64.zip && \
    mv loki-linux-amd64 /usr/local/bin/loki && \
    chmod +x /usr/local/bin/loki && \
    rm promtail-linux-amd64.zip loki-linux-amd64.zip
# Expose port 5000
EXPOSE 5000

# Run the Flask app
#CMD ["python", "app.py"]
CMD ["/app/start_services.sh"]