apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      timeInterval: "5s"
      
  - name: Loki
    type: loki
    access: proxy
    url: http://flask-app:3100
    isDefault: false
    jsonData:
      maxLines: 1000
